
CREATE TABLE IF NOT EXISTS CLIENT_TABLE
(
    ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME  VARCHAR(128) NOT NULL,
    LAST_NAME   VARCHAR(128) NOT NULL,
    MIDDLE_NAME VARCHAR(128) NOT NULL,
    SECRET_WORD TEXT         NOT NULL
);


INSERT INTO CLIENT_TABLE (FIRST_NAME, LAST_NAME, MIDDLE_NAME, SECRET_WORD)
VALUES ('Ivan', 'Ivanov', 'Ivanovich', '$2y$10$JX7PS96aweY6CePOlU3itutKtNv3kwYyoisQoqsGVzYMtMc1acWRu');

INSERT INTO CLIENT_TABLE (FIRST_NAME, LAST_NAME, MIDDLE_NAME, SECRET_WORD)
VALUES ('Vasiliy', 'Vasilyev', 'Vasilyevich', '$2y$10$3gTWSlB.AA3.PD9je/qoHeAmWINv9mC7DdQs5PxRguZMzxBcP/QGO');
