
CREATE TABLE IF NOT EXISTS ACCOUNT_TABLE
(
    ID                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_CLIENT_ID      BIGINT NOT NULL,
    NUMBER            BIGINT NOT NULL,
    SUM               DECIMAL NOT NULL,
    ACCOUNT_TYPE      VARCHAR(32),
    REGISTRATION_DATE TIMESTAMP NOT NULL,
    EXPIRATION_DATE   TIMESTAMP NOT NULL
);

INSERT INTO ACCOUNT_TABLE (FK_CLIENT_ID, NUMBER, SUM, ACCOUNT_TYPE, REGISTRATION_DATE, EXPIRATION_DATE)
VALUES (1, 123, 100000, NULL, '2018-10-19'::timestamp, '2022-10-19'::timestamp);

INSERT INTO ACCOUNT_TABLE (FK_CLIENT_ID, NUMBER, SUM, ACCOUNT_TYPE, REGISTRATION_DATE, EXPIRATION_DATE)
VALUES (2, 321, 100000, NULL, '2019-10-19'::timestamp, '2023-10-19'::timestamp);

