CREATE TABLE IF NOT EXISTS TRANSACTION_TABLE
(
    ID               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_CASHORDER_ID  BIGINT,
    FK_ACCOUNT_ID    BIGINT,
    SUM              DECIMAL NOT NULL,
    TRANSACTION_TYPE VARCHAR(32) NOT NULL,
    CREATED_AT       TIMESTAMP NOT NULL,
    IS_SUCCESSFUL    BOOLEAN NOT NULL,
    MESSAGE          VARCHAR(128) NOT NULL
);