
CREATE TABLE IF NOT EXISTS CASHORDER_TABLE
(
    ID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_ACCOUNT_ID BIGINT NOT NULL,
    ORDER_TYPE    VARCHAR(32) NOT NULL,
    SUM           DECIMAL NOT NULL,
    IS_SUCCESSFUL BOOLEAN NOT NULL,
    CREATED_AT    TIMESTAMP NOT NULL,
    MESSAGE       VARCHAR(128) NOT NULL
);